<?php

/**
 * @file
 * Provides hook implementations and functionality for oa_jira_collector.
 */

/**
 * Implements hook_ctools_plugin_directory
 */
function oa_jira_collector_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
* Implements hook_theme()
*/
function oa_jira_collector_theme() {
  $path = drupal_get_path('module', 'oa_jira_collector') . '/templates';
  return array(
    'oa_jira_collector' => array(
    'template'  => 'oa-jira-collector',
    'path' => $path,
    ),
  );
}
